### ISSUE TITLE
the pie chart breaks when we have a lot of different categories

### ISSUE THREAD

**Issue by aagm** [Vizzuality/tocapu#17]
when this happen you have to change the type of graphic to let the graph work again

**Comment by aagm** [comment]
it could be great if it could do something like get the most representative categories and when they exceed a number (ie 10 categories) group together those less representative

**Comment by clementprdhomme** [comment]
It has been addressed in the last merge of develop and in gh-pages.
An example of the changes can be found here: http://vizzuality.github.io/tocapu/#account:simbiotica&table:countries_complete_old&graph:pie&cat:language
